### ISSUE TITLE
Running in development/test without faktory daemon

### ISSUE THREAD

**Issue by kubasub** [cjbottaro/faktory_worker_ex#18]
In day-to-day development that doesn't touch faktory/jobs, I would like to run my phoenix app without needing to run the faktory daemon. The Issue I'm having is that if I start the phoenix app without faktory running, stdout gets flooded with connection failed messages.

Is there a way I can get around this? Is there a way that the worker could be configured not to try to connect -- maybe via a "disable_faktory" flag -- or not to warn me?

The same thing happens when running tests: while the ExUnit tests are running, stdout gets the connection failed warnings.

Any help would be great -- thanks!

**Comment by kubasub** [comment]
I set the the conection pool size to 0, which seems to stop the client from trying to connect -- until I explicitly make a call to enqueue a job via `perform_async/1`. This is a good workaround (if not a solution), but I'd like to know if there is a better way to approach this. Thanks again!

**Comment by cjbottaro** [comment]
Hi! Hmm, that's interesting and seemingly non-traditional, imo.

I feel like it's the equivalent to asking a Rails app to startup without connecting to the database or ignore a Redis initializer or something. Part of me thinks that a dev environment should have hard requirements on what datastores to connect to (Postgres, Redis, Faktory, etc).

If you don't want to connect to a Faktory server in dev, can you just remove the configuration altogether from the Mix configs?

For what it's worth, it's crazy easy to run a Faktory server locally via Docker. See here:
https://github.com/cjbottaro/faktory_worker_ex/blob/master/docker-compose.yml

Using that Docker Compose file, you can just say:

```
docker-compose up -d
```

And you'll have Faktory servers up and running for dev and test (test server will be on a different port).

Hope that helps!

**Comment by cjbottaro** [comment]
> If you don't want to connect to a Faktory server in dev, can you just remove the configuration altogether from the Mix configs?

I now understand that won't work because of this:

> If you don’t configure faktory_worker_ex at all, it will autoconfigure itself to connect to a Faktory server on localhost both client side and worker side with sane defaults.

**Comment by acj** [comment]
If you won't be interacting with faktory during dev/test, then you can prevent the `faktory_worker_ex` app dependency from starting by providing the `runtime` keyword like so:

```ex
# mix.exs
defp deps do
  # [...]
  {:faktory_worker_ex, "~> 0.5.0", runtime: Mix.env == :prod}
end
```

The code will still be compiled and included, but you shouldn't see the connection warnings anymore.

**Comment by kubasub** [comment]
@cjbottaro what you're saying with having faktory running as a requirement _does_ make sense to me for dev. I'll be sure to consider adding this into my workflow at some point!

@acj It looks like that is exactly what I was asking for, thanks!

Thanks for the help @cjbottaro and @acj !!
