### ISSUE TITLE
Connection warnings on test environment

### ISSUE THREAD

**Issue by max-konin** [cjbottaro/faktory_worker_ex#20]
Hello. 

When I run my test I get warning messages:
[warn] [faktory] Connection failed to localhost:7419 (econnrefused)

I tried to add `Mox.defmock(Faktory.Tcp.Mock, for: Faktory.Tcp)` to my test_helper. But messages still appear.

**Comment by cjbottaro** [comment]
Sorry, I just now saw this. There is something wrong with my Github notifications. I will look into it.

**Comment by cjbottaro** [comment]
When you say your tests, do you mean your project's tests? Or `faktory_worker_ex`'s tests?

If you mean your project's tests, and they don't depend on Faktory, then see this comment:
https://github.com/cjbottaro/faktory_worker_ex/issues/18#issuecomment-368837229

But yeah, this is an issue. I wanted to make `faktory_worker_ex` "zero conf", which means if you don't configure it at all, it makes some assumptions. Namely, attempting to connect to "localhost:7419".

Maybe we should look to Ecto for inspiration and _require_ configuration. If there is no configuration, then don't try to connect to a server.

**Comment by max-konin** [comment]
Hi

> If you mean your project's tests, and they don't depend on Faktory, then see this comment:
#18 (comment)

it might work. thx
