### ISSUE TITLE
Rewrite config system to be like Ecto

### ISSUE THREAD

**Issue by cjbottaro** [cjbottaro/faktory_worker_ex#8]
I love Ecto's decoupling of query generation from query execution. One can generate a query, then execute it against different databases. That idea can be useful here, especially for testing.

```elixir
config :faktory_worker_ex, FaktoryClient1,
  host: "faktory1.mycompany.com",
  default: true

config :faktory_worker_ex, FaktoryClient2,
  host: "faktory2.mycompany.com"
```

```elixir
defmodule FaktoryClient1 do
  use Faktory.ClientConfig

  def init(config) do
    # Do dynamic config here
    Map.put(config, :port, 1111)
  end
end

defmodule FaktoryClient2 do
  use Faktory.ClientConfig

  def init(config) do
    # Do dynamic config here
    Map.put(config, :port, 1111)
  end
end
```

```elixir
args = [1, 2, "hello"]
MyFunJob.perform_async(args, client: FaktoryClient1)
MyFunJob.perform_async(args, client: FaktoryClient2)
MyFunJob.perform_async(args) # uses default
```

Workers (the things that fetch/process) to be configured the same way.

My only question is how to specify the default client?
1. First defined?
1. Explicit with config key?
1. If only one client is configured, do you still have to specify the `:default` config key?

cc @acj

**Comment by valo** [comment]
May be the workers should specify the client they are hooked to?

**Comment by cjbottaro** [comment]
I think that should be the responsibility of the programmer who is making the calls to `perform_async`. I think it would be really difficult dynamically update calls to `perform_async` depending on which worker its being called under.

**Comment by valo** [comment]
Or may be reverse the order, like this:

```elixir
FaktoryClient1.perform_async(MyFunJob, args)
```

It is an interesting question how the workers will get invoked when a job arrives from faktory. Does the registration of the worker module happen in the workers or in the clients? May be it makes sense to define them in the clients?

**Comment by acj** [comment]
I don't have much to add here, but I'd vote for explicitly specifying the default unless there's only one client. If you don't specify a default in a multi-client setup, then raise (or just pick one).
